on:
  release:
    types:
      - released
  push:
    tags:
      - v*.*.*

jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - run: true
        if: | ((
              github.event_name == 'push'
              || github.event_name == 'workflow_dispatch'
            )
            && github.head_ref == ''
            && github.base_ref == ''
            && github.event.repository.owner.name == 'DeterminateSystems'
            && github.repository_owner == 'DeterminateSystems'
            && github.ref_type == 'tag'
          )
