on:
  release:
    types:
      - released
  push:
    tags:
      - v*.*.*

jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$HI"
        env:
          HI: ${{ toJson(github) }}
      - run: "true"
        if: |
          ((
              github.event_name == 'push'
              || github.event_name == 'workflow_dispatch'
              || github.event_name == 'release'
            )
            && github.head_ref == ''
            && github.base_ref == ''
            && github.ref_type == 'tag'
            && github.repository_owner == 'grahamc'
            && github.event.repository.owner.name == 'grahamc'
          )
